### ISSUE TITLE
Logging to a Level 1 character and back to Main character resets Data

### ISSUE THREAD

**Issue by Nelythia** [kakysha/HonorSpy#74] opened 2019-12-02 02:58 UTC
I logged on a few of my bankchars today to resupply my main with potions, bandages etc. While logging on one of the lvl 1s the addon decided to purge all data. I didn't think much about it and thought it may just have had old data from getting it previously shared somehow.

Well, after logging on my main again, it purged the data there as well. I lost my pool of 3000 entries and now I have to somehow get it synced asap again to have accurate pool size and data.

**Comment by kakysha** [comment] 2019-12-02 09:50
Can't reproduce. Same server? Same faction? It should not be possible, as character data (honor) is saved under character's database, and server faction-wide database is shared across faction on one server.

**Comment by Nelythia** [comment] 2019-12-02 13:47
Same server and faction.

Shazzrah Horde - Nelybank, Nelyore, Nelyoretwo, Nelycloth, Nelyherb, Nelyele. I logged through a few of those, then at some point it reset the data while being on the level 1. 
Logging back to my main Nelythia reset the data there as well.

That was using HonorSpy 1.5.6 btw, I have since updated it to 1.5.9.

**Comment by kakysha** [comment] 2019-12-02 15:58
Was it a "weekly reset"? If it was, your addon will discard now every person who has "last seen" before your reset time. So check every person's last seen, it should be not longer than 1d or something, when you had a reset. And if it is, then try remember what actions you did with your db? or maybe savedvars?

**Comment by Nelythia** [comment] 2019-12-02 16:17
I think it was a weekly reset based on the fact that I got 2 chat messages from the purge data on both characters. But my data did not have any old data, we made sure that people use the updated version now to prevent the duplicate and old data issue. The pool size was also at 3000 compared to having 6000-8000 in the first 2 weeks with older entries.

I didn't modify HonorSpy or touch it at all while logging onto the bank characters and back to the main. It simply just decided to do a reset.

**Comment by kakysha** [comment] 2019-12-02 18:22
did any of them had some honor?

**Comment by Nelythia** [comment] 2019-12-02 20:27
No the level 1s never left Orgrimmar

**Comment by kakysha** [comment] 2019-12-03 00:01
Then I had no ideas left :) Can you probably send me your */WTF/Account/SavedVars/HonorSpy.lua file with tour saved varliables?

**Comment by Nelythia** [comment] 2019-12-03 00:05
https://workupload.com/file/US2897ef

**Comment by dagochen** [comment] 2019-12-04 06:51
I tried it too, but had no problems.

**Comment by kakysha** [comment] 2019-12-16 18:29
closing for now, can't reproduce

**Closed as completed by kakysha** 2019-12-16 18:29 UTC
