### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by OzCymru** [kakysha/HonorSpy#162] opened 2021-12-13 13:30 UTC
When I press the button to export to CSV nothing happens.
I'm assuming it should be opening a window with the CSV formatted text to be able to be copied?

Edit: I had errors disabled, but it upon showing them I get the following when I press Export:

```
Message: Interface\AddOns\honorspy\export.lua:59: attempt to index local 'editbox' (a nil value)
Time: Mon Dec 13 13:40:51 2021
Count: 2
Stack: Interface\AddOns\honorspy\export.lua:59: attempt to index local 'editbox' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\honorspy\export.lua"]:59: in function `ExportCSV'
[string "@Interface\AddOns\honorspy\settings.lua"]:95: in function <Interface\AddOns\honorspy\settings.lua:95>
[string "=[C]"]: ?
[string "@Interface\AddOns\ClassicCastbars_Options\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Interface\AddOns\ClassicCastbars_Options\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:847: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:668>
[string "=[C]"]: ?
[string "@Interface\AddOns\Dejunk\libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...terface\AddOns\Dejunk\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Dejunk\libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\BGQueueTracker\Libs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua"]:22: in function <...Libs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

Locals: <none>
```

**Comment by Aleks1015** [comment] 2021-12-14 05:55
This is an issue caused by the movement to the Shadowlands client for Classic/Classic Era.  I added a fix for this to go along with the EU realm list fix.

**Closed as completed** 2021-12-14 09:59 UTC
