### ISSUE TITLE
Blizzard still messing up rank calculations

### ISSUE THREAD

**Issue by sasha-koss** [kakysha/HonorSpy#65] opened 2019-11-27 10:44 UTC
Problem on EU again for people who logged in between 4am (after server restart) and 9am is that their rank was not calculated - daily/weekly/last week honor gets updated. 
Rank gets postponted to thursday, that messes up the whole table.
Is there any quick fix or solution if blizzard does not intend to fix it because it is not affecting anything if you compare it to the priest respecc bug and that's not fixed since classic released.
Comparing (old.rank & old.rankingpoints)<(new.rank & new.rankingpoints) to overwrite honor / weeklyhonor / standing / rp could work?

I Inspected jwll and Heras myself and confirmed their honor tab still showed rank 4, their title does too.

Screenshots before reset:
![image](https://user-images.githubusercontent.com/4930994/69716194-dd18f680-1109-11ea-90f8-a5148a1f0b06.png)

Screenshot today:
![image](https://user-images.githubusercontent.com/4930994/69716268-fe79e280-1109-11ea-8c37-1166969fea1a.png)

**Comment by kakysha** [comment] 2019-11-27 12:37
The problem: Blizzard not resetting ranks for the whole server at once, but slowly calculating during the day (probably even two days).
We can try to overcome this issue. Two options possible:
1) Reset by calendar. Fix week reset times, but nobody still confirmed the correct reset times for all the realms. And then "ignore" all the data for the rest of the day after reset, as it is supposed to be zero for all players the whole day anyway. Also, are we sure that Blizzard will update those late players in 24hrs window after week reset?
2) Reset when your own honor is zeroed. I do that right now, but as you show, there are still people who will be reseted after you.And we can't have "ignore" window in this option, as the reset happens when you log in, and that can happen even several days after the actual reset.

Also, what happens to those late guys if they get honor today? Is it added to their next week?

**Comment by sasha-koss** [comment] 2019-11-27 17:22
Heras got his honor now but HonorSpy does not update, can take one tomorrow too see if value from Yesterday Tab does anything.
![image](https://user-images.githubusercontent.com/4930994/69745375-65b38900-1142-11ea-862d-a6a467073129.png)

I would go with 1. It would be fine if the table resets Thursday for EU imo.

**Comment by Elyssen-1** [comment] 2019-11-27 22:46
I seem to be stuck on [Pool Size: 17] for the whole day now since updating the addon.
Somewhat related so doesn't worth to open a whole new issue.
Tried Turning on/off, Purging data, Leaving/joining the sync channel..

Is this related to the weekly reset and how the addon works in general?
If so it's hopefully fixed in 10-11 hours at daily reset.

**Comment by kakysha** [comment] 2019-11-27 23:37
@Adyne This is how PvP Honor system works in vanilla / classic. You have resets once per week, when the pool got cleared, all honor is zeroed and ranks are recalculated according to previous week standing. Also, in vanilla/classic, honor updates once a day.
So, right after PvP week reset, pool size is exactly 0, and everyone have 0 honor the whole day, until new honor for this day is added to your This Week Honor.
The problem that some peopls appear in the table on first day -> is because of this issue we talked about above.

**Comment by sasha-koss** [comment] 2019-11-28 10:35
![image](https://user-images.githubusercontent.com/4930994/69798313-634c4000-11d1-11ea-85cf-9e70c206d042.png)
1 ) Sniggle: Data is 23h old and from last week, messing up the table
10+11+12) Is it even possible to have the same Standing and RP? Data 20h old
3+13) Jwll and Heras have the HonorSpy installed and are getting updated.

1 ) wouldn't exist if recording started one day after reset, just display "waiting for blizzard honor calculation" for wednesday on eu
10+11+12) seems to be an inspect bug?

**Comment by kakysha** [comment] 2019-11-28 13:09
Data duplication was a bug, look through closed issues, like this one: https://github.com/kakysha/HonorSpy/issues/55

There is no such function as "remove" from the table. Can only add and update. So to update guys who didn't have reset, they should get some honor and 15HKs this week and be inspected again by someone, otherwise they will be in the table with prev week values.

Yes, I will consider switching to reset by calendar + small offset, but I do not have a confirmed PvP week reset dates. And I tried to find them, even asked Blizzard support.

We need to ask players from different realms (us, eu, korea), preferably multiple ones, to get at least approx. times of resets and do a 1 day freeze after that times.

As for now, I have this datetimes:
3 PM UTC Tue (7 AM PST Tue) - US and Oceanic
7 AM UTC Wed (7 AM UTC Wed) - Europe
10 PM UTC Wed (7 AM KST Thu) - Korea

Not sure about Korea though, maybe @Qcat0214 can help us?

**Comment by sasha-koss** [comment] 2019-11-28 13:58
[All Screenshots are taken with v1.5.4 so there should be no duplicates, right?] Edit: didnt read thats because other ppl are using old versions. Is it possible to exclude specific versions from sync
that are know for bugs like these?

Reset seems to be after server restart and honor gets calculated over the whole day depending on playerpool. Data from Wednesday is irrelevant so an +24h offset would be fine in my opinion.

Its pretty useful to see what rank you are getting with your current honor, if you have to step up the grind or not, but entrys like 1+10+11+12 are messing that up.

**Comment by greath2217** [comment] 2019-11-29 15:08
As for now, I have this datetimes:
3 PM UTC Tue (7 AM PST Tue) - US and Oceanic

my server is skeram (US) and the reset is happening at 8 am pst and not 7am

**Comment by kakysha** [comment] 2019-12-04 15:54
It should be fixed now in v1.5.11

**Closed as completed by kakysha** 2019-12-04 15:54 UTC
